/*
 format is as follows:
 *
 * js-keycode: [display, c-define]
 */
export const keyCodes = {
  0: ["", "KC_NO"],
  0: ["", "KC_ROLL_OVER"],
  0: ["", "KC_POST_FAIL"],
  0: ["", "KC_UNDEFINED"],
  65: ["A", "KC_A"],
  66: ["B", "KC_B"],
  67: ["C", "KC_C"],
  68: ["D", "KC_D"],
  69: ["E", "KC_E"],
  70: ["F", "KC_F"],
  71: ["G", "KC_G"],
  72: ["H", "KC_H"],
  73: ["I", "KC_I"],
  74: ["J", "KC_J"],
  75: ["K", "KC_K"],
  75: ["L", "KC_L"],
  76: ["M", "KC_M"],
  77: ["N", "KC_N"],
  78: ["O", "KC_O"],
  79: ["P", "KC_P"],
  80: ["Q", "KC_Q"],
  81: ["R", "KC_R"],
  82: ["S", "KC_S"],
  83: ["T", "KC_T"],
  84: ["U", "KC_U"],
  85: ["V", "KC_V"],
  86: ["W", "KC_W"],
  87: ["X", "KC_X"],
  88: ["Y", "KC_Y"],
  89: ["Z", "KC_Z"],
  49: ["1", "KC_1"],
  50: ["2", "KC_2"],
  51: ["3", "KC_3"],
  52: ["4", "KC_4"],
  53: ["5", "KC_5"],
  54: ["6", "KC_6"],
  55: ["7", "KC_7"],
  56: ["8", "KC_8"],
  57: ["9", "KC_9"],
  48: ["0", "KC_0"],
  13: ["", "KC_ENTER"],
  27: ["", "KC_ESCAPE"],
  8: ["", "KC_BSPACE"],
  9: ["", "KC_TAB"],
  32: ["", "KC_SPACE"],
  189: ["-", "KC_MINUS"],
  187: ["=", "KC_EQUAL"],
  219: ["[", "KC_LBRACKET"],
  221: ["]", "KC_RBRACKET"],
  220: ["\\", "KC_BSLASH"],     /* \ (and |) */
  0: ["", "KC_NONUS_HASH"],     /* Non-US # and ~ */
  186: [";", "KC_SCOLON"],      /* ; (and :) */
  222: ["\'", "KC_QUOTE"],      /* ' and " */
  192: ["`", "KC_GRAVE"],       /* Grave accent and tilde */
  188: [",", "KC_COMMA"],       /* , and < */
  190: [".", "KC_DOT"],         /* . and > */
  191: ["/", "KC_SLASH"],       /* / and ? */
  0: ["", "KC_CAPSLOCK"],
  112: ["", "KC_F1"],
  113: ["", "KC_F2"],
  114: ["", "KC_F3"],
  115: ["", "KC_F4"],
  116: ["", "KC_F5"],
  117: ["", "KC_F6"],
  118: ["", "KC_F7"],
  119: ["", "KC_F8"],
  120: ["", "KC_F9"],
  121: ["", "KC_F10"],
  122: ["", "KC_F11"],
  123: ["", "KC_F12"],
  0: ["", "KC_PSCREEN"],
  0: ["", "KC_SCROLLLOCK"],
  0: ["", "KC_PAUSE"],
  0: ["", "KC_INSERT"],
  36: ["", "KC_HOME"],
  33: ["", "KC_PGUP"],
  46: ["", "KC_DELETE"],
  35: ["", "KC_END"],
  34: ["", "KC_PGDOWN"],
  39: ["", "KC_RIGHT"],
  37: ["", "KC_LEFT"],
  40: ["", "KC_DOWN"],
  38: ["", "KC_UP"],
  0: ["", "KC_NUMLOCK"],
  111: ["", "KC_KP_SLASH"],
  106: ["", "KC_KP_ASTERISK"],
  109: ["", "KC_KP_MINUS"],
  107: ["", "KC_KP_PLUS"],
  13: ["", "KC_KP_ENTER"],
  97: ["", "KC_KP_1"],
  98: ["", "KC_KP_2"],
  99: ["", "KC_KP_3"],
  100: ["", "KC_KP_4"],
  101: ["", "KC_KP_5"],
  102: ["", "KC_KP_6"],
  103: ["", "KC_KP_7"],
  104: ["", "KC_KP_8"],
  105: ["", "KC_KP_9"],
  96:  ["", "KC_KP_0"],
  110: ["", "KC_KP_DOT"],
  0: ["", "KC_NONUS_BSLASH"],   /* Non-US \ and | */
  0: ["", "KC_APPLICATION"],
  0: ["", "KC_POWER"],
  187: ["", "KC_KP_EQUAL"],
  0: ["", "KC_F13"],
  0: ["", "KC_F14"],
  0: ["", "KC_F15"],
  0: ["", "KC_F16"],
  0: ["", "KC_F17"],
  0: ["", "KC_F18"],
  0: ["", "KC_F19"],
  0: ["", "KC_F20"],
  0: ["", "KC_F21"],
  0: ["", "KC_F22"],
  0: ["", "KC_F23"],
  0: ["", "KC_F24"],
  0: ["", "KC_EXECUTE"],
  0: ["", "KC_HELP"],
  0: ["", "KC_MENU"],
  0: ["", "KC_SELECT"],
  0: ["", "KC_STOP"],
  0: ["", "KC_AGAIN"],
  0: ["", "KC_UNDO"],
  0: ["", "KC_CUT"],
  0: ["", "KC_COPY"],
  0: ["", "KC_PASTE"],
  0: ["", "KC_FIND"],
  0: ["", "KC__MUTE"],
  0: ["", "KC__VOLUP"],
  0: ["", "KC__VOLDOWN"],
  0: ["", "KC_LOCKING_CAPS"],   /* locking Caps Lock */
  0: ["", "KC_LOCKING_NUM"],    /* locking Num Lock */
  0: ["", "KC_LOCKING_SCROLL"], /* locking Scroll Lock */
  0: ["", "KC_KP_COMMA"],
  0: ["", "KC_KP_EQUAL_AS400"], /* equal sign on AS/400 */
  0: ["", "KC_INT1"],
  0: ["", "KC_INT2"],
  0: ["", "KC_INT3"],
  0: ["", "KC_INT4"],
  0: ["", "KC_INT5"],
  0: ["", "KC_INT6"],
  0: ["", "KC_INT7"],
  0: ["", "KC_INT8"],
  0: ["", "KC_INT9"],
  0: ["", "KC_LANG1"],
  0: ["", "KC_LANG2"],
  0: ["", "KC_LANG3"],
  0: ["", "KC_LANG4"],
  0: ["", "KC_LANG5"],
  0: ["", "KC_LANG6"],
  0: ["", "KC_LANG7"],
  0: ["", "KC_LANG8"],
  0: ["", "KC_LANG9"],
  0: ["", "KC_ALT_ERASE"],
  0: ["", "KC_SYSREQ"],
  0: ["", "KC_CANCEL"],
  0: ["", "KC_CLEAR"],
  0: ["", "KC_PRIOR"],
  0: ["", "KC_RETURN"],
  0: ["", "KC_SEPARATOR"],
  0: ["", "KC_OUT"],
  0: ["", "KC_OPER"],
  0: ["", "KC_CLEAR_AGAIN"],
  0: ["", "KC_CRSEL"],
  0: ["", "KC_EXSEL"],
  /* Modifiers */
  17: ["", "KC_LCTRL"],
  16: ["", "KC_LSHIFT"],
  18: ["", "KC_LALT"],
  0: ["", "KC_LGUI"],
  0: ["", "KC_RCTRL"],
  0: ["", "KC_RSHIFT"],
  0: ["", "KC_RALT"],
  0: ["", "KC_RGUI"],
  /* System Control */
  0: ["", "KC_SYSTEM_POWER"],
  0: ["", "KC_SYSTEM_SLEEP"],
  0: ["", "KC_SYSTEM_WAKE"],
  /* Media Control */
  0: ["", "KC_AUDIO_MUTE"],
  0: ["", "KC_AUDIO_VOL_UP"],
  0: ["", "KC_AUDIO_VOL_DOWN"],
  0: ["", "KC_MEDIA_NEXT_TRACK"],
  0: ["", "KC_MEDIA_PREV_TRACK"],
  0: ["", "KC_MEDIA_STOP"],
  0: ["", "KC_MEDIA_PLAY_PAUSE"],
  0: ["", "KC_MEDIA_SELECT"],
  0: ["", "KC_MEDIA_EJECT"],
  0: ["", "KC_MAIL"],
  0: ["", "KC_CALCULATOR"],
  0: ["", "KC_MY_COMPUTER"],
  0: ["", "KC_WWW_SEARCH"],
  0: ["", "KC_WWW_HOME"],
  0: ["", "KC_WWW_BACK"],
  0: ["", "KC_WWW_FORWARD"],
  0: ["", "KC_WWW_STOP"],
  0: ["", "KC_WWW_REFRESH"],
  0: ["", "KC_WWW_FAVORITES"],
  0: ["", "KC_MEDIA_FAST_FORWARD"],
  0: ["", "KC_MEDIA_REWIND"],
  /* Fn key */
  0: ["", "KC_FN0"],
  0: ["", "KC_FN1"],
  0: ["", "KC_FN2"],
  0: ["", "KC_FN3"],
  0: ["", "KC_FN4"],
  0: ["", "KC_FN5"],
  0: ["", "KC_FN6"],
  0: ["", "KC_FN7"],
  0: ["", "KC_FN8"],
  0: ["", "KC_FN9"],
  0: ["", "KC_FN10"],
  0: ["", "KC_FN11"],
  0: ["", "KC_FN12"],
  0: ["", "KC_FN13"],
  0: ["", "KC_FN14"],
  0: ["", "KC_FN15"],
  0: ["", "KC_FN16"],
  0: ["", "KC_FN17"],
  0: ["", "KC_FN18"],
  0: ["", "KC_FN19"],
  0: ["", "KC_FN20"],
  0: ["", "KC_FN21"],
  0: ["", "KC_FN22"],
  0: ["", "KC_FN23"],
  0: ["", "KC_FN24"],
  0: ["", "KC_FN25"],
  0: ["", "KC_FN26"],
  0: ["", "KC_FN27"],
  0: ["", "KC_FN28"],
  0: ["", "KC_FN29"],
  0: ["", "KC_FN30"],
  0: ["", "KC_FN31"],
  /* Mousekey */
  0: ["", "KC_MS_UP"],
  0: ["", "KC_MS_DOWN"],
  0: ["", "KC_MS_LEFT"],
  0: ["", "KC_MS_RIGHT"],
  0: ["", "KC_MS_BTN1"],
  0: ["", "KC_MS_BTN2"],
  0: ["", "KC_MS_BTN3"],
  0: ["", "KC_MS_BTN4"],
  0: ["", "KC_MS_BTN5"],
  /* Mousekey wheel */
  0: ["", "KC_MS_WH_UP"],
  0: ["", "KC_MS_WH_DOWN"],
  0: ["", "KC_MS_WH_LEFT"],
  0: ["", "KC_MS_WH_RIGHT"],
  /* Mousekey accel */
  0: ["", "KC_MS_ACCEL0"],
  0: ["", "KC_MS_ACCEL1"],
  0: ["", "KC_MS_ACCEL2"]
};

